# Generated by Django 3.1.1 on 2020-09-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('user_IP', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('request_method', models.CharField(blank=True, max_length=30, null=True)),
                ('request_path', models.CharField(blank=True, max_length=255, null=True)),
                ('status_code', models.CharField(blank=True, max_length=50, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
